## spring security 配置
security:
  oauth2:
    client:
      client-id: spark
      client-secret: spark
      scope: server
      # 默认放行url,子模块重写时application-dev.yml中的公共配置会被覆盖,所以要把公共配置中的放行url再写一次
      ignore-urls:
        - /actuator/**
        - /v2/api-docs
        - /user/info/*
        - /social/info/*
        - /log/save

# 数据源 连接池：HikariCP
#spring:
#  datasource:
#    type: com.zaxxer.hikari.HikariDataSource
#    driver-class-name: com.mysql.jdbc.Driver
#    username: rrsadtest
#    password: Rrsad_test
#    url: jdbc:mysql://rm-m5e31ll958y0a0j5fqo.mysql.rds.aliyuncs.com:3306/spark?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false

# 数据源 连接池：druid 阿里带前台监控
spring:
    mvc:
      view:
        prefix: /WEB-INF/view/
        suffix: .jsp
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        driver-class-name: com.mysql.jdbc.Driver
        platform: mysql
        url: jdbc:mysql://spark-mysql:3306/ztframework?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: 1qaz!QAZ
        initialSize: 5
        minIdle: 5
        maxActive: 20
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT1FROMDUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        filters: stat,wall,log4j
        logSlowSql: true

# mybaits 模块配置
mybatis-plus:
  #typeAliasesPackage: com.ztman.admin.api.entity
  typeAliasesPackage: com.ztman.admin.api.entity,com.ztman.*.*.domain,com.ztman.*.*.entity,com.ztman.*.*.model

# swagger相关配置,覆盖全局配置
swagger:
  authorization:
    authorization-scope-list:
      - scope: 'server'
        description: 'server all'
      - scope: 'read'
        description: 'read all'
      - scope: 'write'
        description: 'access all'
