# 数据源
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1qaz!QAZ
    url: jdbc:mysql://spark-mysql:3306/ztframework?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
