## spring security 配置
security:
  oauth2:
    client:
      client-id: spark
      client-secret: spark
      scope: server

# 数据源 连接池：HikariCP
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1qaz!QAZ
    url: jdbc:mysql://spark-mysql:3306/ztframework?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false

# mybaits 模块配置
mybatis-plus:
  #typeAliasesPackage: com.ztman.admin.api.entity
  typeAliasesPackage: com.ztman.business.inspection.com.ztman.business.inspection.client.entity,com.ztman.*.*.domain,com.ztman.*.*.entity,com.ztman.*.*.model

