## spring security 配置
security:
  oauth2:
    client:
      client-id: spark
      client-secret: spark
      scope: server

# 数据源配置
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1qaz!QAZ
    url: jdbc:mysql://spark-mysql:3306/ztframework?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  resources:
    static-locations: classpath:/static/,classpath:/views/

# mybaits 模块配置
mybatis-plus:
  typeAliasesPackage: com.ztman.codegen.entity

