spring:
  cloud:
    gateway:
      locator:
        enabled: true
      routes:
      # 认证中心
      - id: auth
        #lb代表从注册中心获取服务
        uri: lb://auth
        #转发路径配置
        predicates:
        - Path=/auth/**
        filters:
          # 验证码处理
        - ImageCodeGatewayFilter
          # 前端密码解密
        - PasswordDecoderFilter
          #将路径中的Path前缀剥离
        - StripPrefix=1
      #UPMS 模块
      - id: admin
        uri: lb://admin
        predicates:
        - Path=/admin/**
        filters:
          # Swagger请求头处理
        - SwaggerHeaderFilter
          # 请求头清理避免不合法请求头
        - name: RemoveRequestHeader
          args:
            name: from
          # 限流配置
        - name: RequestRateLimiter
          args:
            key-resolver: '#{@remoteAddrKeyResolver}'
            redis-rate-limiter.replenishRate: 50
            redis-rate-limiter.burstCapacity: 100
        - StripPrefix=1
          # 降级配置
        - name: Hystrix
          args:
            name: default
            fallbackUri: 'forward:/fallback'
      # 巡警通
      - id: business-inspection
        uri: lb://business-inspection
        predicates:
        - Path=/inspection/**
        filters:
        - StripPrefix=1
      # 代码生成模块
      - id: codegen
        uri: lb://codegen
        predicates:
        - Path=/gen/**
        filters:
        - StripPrefix=1
      # 代码生成模块
      - id: zt-spark
        uri: lb://zt-spark
        predicates:
          - Path=/spark/**
        filters:
          - StripPrefix=1
      - id: ztman-bpm
        uri: lb://ztman-bpm
        predicates:
          - Path=/bpm/**
        filters:
          - StripPrefix=1
          # Swagger请求头处理
          - SwaggerHeaderFilter
          # 请求头清理避免不合法请求头


security:
  encode:
    # 前端密码密钥，必须16位
    key: 'sparkspark123456'

# 不校验验证码终端
ignore:
  clients:
    - test
