export default {
  title: 'Tunny',
  logo: 'Tunny',
  author: '开发框架',
  whiteList: ['/login', '/404', '/401', '/lock', '/authredirect','/reset'],
  tokenTime: 6000,
  info: {
      title: 'Tunny PaaS服务开发框架',
      list: [
          '是一个基于Spring Cloud、oAuth2.0开发基于Vue前后分离的开发平台',
          ' 是一个基于vue+vuex+vue-router快速后台管理系统，采用token交互验证方式。',
          '最大程度上帮助企业节省时间成本和费用开支。 ',
          '当前版本：v1.0.0'
        ]
    },
  wel: {
      title: 'Tunny PaaS服务开发框架',
      list: [
          '是一个基于Spring Cloud、oAuth2.0开发基于Vue前后分离的开发平台',
          ' 是一个基于vue+vuex+vue-router快速后台管理系统，采用token交互验证方式。',
          '最大程度上帮助企业节省时间成本和费用开支。 ',
          '当前版本：v1.0.0'
        ]
    },
  iconList:[
    'icon-tunny-guanli',
    'icon-tunny-caidan1',
    'icon-tunny-shezhi2',
    'icon-tunny-icon_refresh',
    'icon-tunny-yanse',
    'icon-tunny-shouye',
    'icon-tunny-shouqian',
    'icon-tunny-yunzhujipitchon',
    'icon-tunny-fangda',
    'icon-tunny-tunny-xiangmuguanli',
    'icon-tunny-fuwu-active',
    'icon-tunny-shezhi1',
    'icon-tunny-xiaoxi',
    'icon-tunny-tunny-dangan',
    'icon-tunny-EECACE',
    'icon-tunny-shujuku',
    'icon-tunny-changjingguanli',
    'icon-tunny-bianji',
    'icon-tunny-guanfangbanben',
    'icon-tunny-gongnengdingyi',
    'icon-tunny-hezuohuobanmiyueguanli',
    'icon-tunny-ceshishenqing',
    'icon-tunny-jiedianguanli',
    'icon-tunny-jinggao',
    'icon-tunny-peiwangyindao',
    'icon-tunny-shiyongwendang',
    'icon-tunny-yishouquan',
    'icon-tunny-tianshenpi',
    'icon-tunny-shujukanban',
    'icon-tunny-yingyongguanli',
    'icon-tunny-zhanghaoquanxianguanli',
    'icon-tunny-zhunbeiliangchan',
    'icon-tunny-fanganmoni',
    'icon-tunny-guanbi',
    'icon-tunny-zidingyi',
    'icon-tunny-xiajiantou',
    'icon-tunny-shangjiantou',
    'icon-tunny-icon_renwujincheng',
    'icon-tunny-icon_fabu',
    'icon-tunny-icon_tianjia',
    'icon-tunny-icon_yulan',
    'icon-tunny-icon_zhanghao',
    'icon-tunny-icon_wangye',
    'icon-tunny-icon_shezhi',
    'icon-tunny-icon_baocun',
    'icon-tunny-icon_yingyongguanli',
    'icon-tunny-icon_shiyongwendang',
    'icon-tunny-icon_bangzhuwendang',
    'icon-tunny-tubiao-bingtu',
    'icon-tunny-gongyezujian-zhishideng',
    'icon-tunny-tubiao-zhexiantu',
    'icon-tunny-tubiao-zhuzhuangtu',
    'icon-tunny-xingzhuang-tupian',
    'icon-tunny-dakai',
    'icon-tunny-kongxinduigou',
    'icon-tunny-huixingzhen',
    'icon-tunny-duigou',
    'icon-tunny-xiayibu',
    'icon-tunny-shangyibu',
    'icon-tunny-kongjianxuanzhong',
    'icon-tunny-kongjianweixuan',
    'icon-tunny-kongjianyixuan',
    'icon-tunny-shuaxin',
    'icon-tunny-baocun',
    'icon-tunny-fabu',
    'icon-tunny-xiangxiazhanhang',
    'icon-tunny-xiangshangzhanhang',
    'icon-tunny-dayin',
    'icon-tunny-suoxiao',
    'icon-tunny-fangda1',
    'icon-tunny-huanyuanhuabu',
    'icon-tunny-quanping',
    'icon-tunny-APIshuchu',
    'icon-tunny-APIjieru',
    'icon-tunny-wenjianjia',
    'icon-tunny-weizhigeshi',
    'icon-tunny-gengduo',
    'icon-tunny-yunduanxiazai',
    'icon-tunny-yunduanshangchuan',
    'icon-tunny-gaojing',
    'icon-tunny-kefu',
    'icon-tunny-sousuobianxiao',
    'icon-tunny-sousuofangda',
    'icon-tunny-dingwei',
    'icon-tunny-pingtai',
    'icon-tunny-gaojing1',
    'icon-tunny-renwujincheng',
    'icon-tunny-xiaoxitongzhi',
    'icon-tunny-youhui',
    'icon-tunny-zhihangfankui',
    'icon-tunny-gongdanqueren',
    'icon-tunny-guangbo',
    'icon-tunny-gongdan',
    'icon-tunny-fork',
    'icon-tunny-xiaoxi1',
    'icon-tunny-chucun',
    'icon-tunny-liebiao',
    'icon-tunny-chengshi',
    'icon-tunny-tupiantianjia',
    'icon-tunny-lvyoushourucesuan',
    'icon-tunny-xiangmulixiangguanli',
    'icon-tunny-caidan',
    'icon-tunny-jiqun',
    'icon-tunny-jiank',
    'icon-tunny-s-yiliaojiankang',
    'icon-tunny-shezhi',
    'icon-tunny-shuaxin1',
    'icon-tunny-wenhao1',
    'icon-tunny-icon_boss',
    'icon-tunny-shenglvehao',
    'icon-tunny-shouji',
    'icon-tunny-youxiang',
    'icon-tunny-saoyisao',
    'icon-tunny-chuguorenyuanshouxubanli',
    'icon-tunny-gengduo1',
    'icon-tunny-f14',
    'icon-tunny-miwen',
    'icon-tunny-tubiao-qiapian',
    'icon-tunny-yuanquyunwei',
    'icon-tunny-shanchu',
    'icon-tunny-ai-password'
  ]
}
